{% set name = "nuke" %}
{% set version = "8.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nuke-build/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 98573ba43b5ad4b9290556ca5a64b18674737a06dd5fced4905a9007acc27623

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - {{ name }} | grep -q "Could not find .nuke directory/file"

about:
  home: https://nuke.build
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The AKEless Build System for C#/.NET
  dev_url: https://github.com/nuke-build/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
