{% set name = "nuke" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nuke-build/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f98c6fb835a1b1280da72e33b773ec275aea61d22a3d0c82ebaad34f5244dcb9

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - {{ name }} | grep -q "Could not find .nuke directory/file"

about:
  home: https://nuke.build
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The AKEless Build System for C#/.NET
  dev_url: https://github.com/nuke-build/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
