{% set name = "nuke" %}
{% set version = "9.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nuke-build/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 2b953e2533d92e201bf9f0779d08cf4abbbc1c171c3fa4a15710c50b896df831

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - {{ name }} | grep -q "Could not find .nuke directory/file"

about:
  home: https://nuke.build
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The AKEless Build System for C#/.NET
  dev_url: https://github.com/nuke-build/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
