context:
  version: "10.0.1"

package:
  name: nuke
  version: ${{ version }}

source:
  url: https://github.com/nuke-build/nuke/archive/${{ version }}.tar.gz
  sha256: a7792ea98af3a62060768847b02dddb51158e2460c9db462fab6145d219920dc

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license 3.0.*
  run:
    - dotnet

tests:
  - script:
      - nuke | grep -q "Could not find .nuke directory/file"

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The AKEless Build System for C#/.NET
  homepage: https://nuke.build
  repository: https://github.com/nuke-build/nuke

extra:
  recipe-maintainers:
    - danielnachun
