context:
  version: "9.0.4"

package:
  name: nuke
  version: ${{ version }}

source:
  url: https://github.com/nuke-build/nuke/archive/${{ version }}.tar.gz
  sha256: 8b5611c07147a6a9b633a79d7e867ccaf99a24704b492c0fc745a9b6f65946fe

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license 3.0.*
  run:
    - dotnet

tests:
  - script:
      - nuke | grep -q "Could not find .nuke directory/file"

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The AKEless Build System for C#/.NET
  homepage: https://nuke.build
  repository: https://github.com/nuke-build/nuke

extra:
  recipe-maintainers:
    - danielnachun
