context:
  version: 8.1.4

package:
  name: nuke
  version: ${{ version }}

source:
  url: https://github.com/nuke-build/nuke/archive/${{ version }}.tar.gz
  sha256: 07bac1d46954935774e785a33e103b4ab6d8dfb2e5b13cf29bc5d50b8bea887f

build:
  number: 1
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - nuke | grep -q "Could not find .nuke directory/file"

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The AKEless Build System for C#/.NET
  homepage: https://nuke.build
  repository: https://github.com/nuke-build/nuke

extra:
  recipe-maintainers:
    - danielnachun
